# Site settings
title: FMS Writes
email: fms1701@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Short Stories in Science Fiction and General Fiction written by Frank Michael Sanchez
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fmswrites.com" # the base hostname & protocol for your site
github_username:  fmswrites
paginate: 10
# Build settings
markdown: kramdown
timezone: America/New_York